### ISSUE TITLE
Permissions keep resetting

### ISSUE THREAD

**Issue by nomadism19** [gauravsuman007/megabasterd-docker#1]
Permissions keep getting reset to “1000/1000” resulting in crash. Manually setting via env in docker compose does not help. Running as part of a larger compose file but this is the only container whose permissions keep resetting.

I am relatively new to using Linux and docker in general so please excuse me if this is a silly concern.

EDIT: ANSWER. Must set env variables for USER_ID and GROUP_ID
https://hub.docker.com/r/jlesage/baseimage-gui

**User/Group IDs**
When using data volumes (-v flags), permissions issues can occur between the host and the container. For example, the user within the container may not exists on the host. This could prevent the host from properly accessing files and folders on the shared volume.

To avoid any problem, you can specify the user the application should run as.

This is done by passing the user ID and group ID to the container via the USER_ID and GROUP_ID environment variables.

To find the right IDs to use, issue the following command on the host, with the user owning the data volume on the host:

id <username>
Which gives an output like this one:

uid=1000(myuser) gid=1000(myuser) groups=1000(myuser),4(adm),24(cdrom),27(sudo),46(plugdev),113(lpadmin)
The value of uid (user ID) and gid (group ID) are the ones that you should be given the container.

**Comment by tekwarfare** [comment]
Thank you for this. The owner was UNKNOWN by default and the container seemed to be ignoring the variables PUID and PGID. Using the names USER_ID and GROUP_ID has fixed this.
