### ISSUE TITLE
[Bug] New versions of Megabasterd require updated JDK

### ISSUE THREAD

**Issue by nomadism19** [gauravsuman007/megabasterd-docker#3]
### Current Behavior

[Please see this thread](https://github.com/tonikelope/megabasterd/issues/599)

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

docker run

### Container log

```text
Unsure how to see logs
```

**Comment by gauravsuman007** [comment]
> ### Current Behavior
> [Please see this thread](https://github.com/tonikelope/megabasterd/issues/599)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Environment
> * OS:
> * OS version:
> * CPU:
> * Docker version:
> * Device model:
> * Browser/OS:
> 
> ### Container creation
> docker run
> 
> ### Container log
> ```
> Unsure how to see logs
> ```
> 
> ### Container inspect
> _No response_
> 
> ### Anything else?
> _No response_

Please provide more information on the megabasterd version and the required JDK version.

I would say that this might be tricky as JDK versions come late to alpine Linux and there may be no support possible until the updated JDK is available. Another option will be to use a Debian based container but it'll be much more bloated

**Comment by workfriend** [comment]
The version of Java that this was experienced in on [megabasterd #599](https://github.com/tonikelope/megabasterd/issues/599) was JDK 8 against MegaBasterd 8.8. Although I was able to resolve the behavior by updating to Open JDK 21, per the interaction with the dev on the aforementioned link, it seems that JDK 11 might work as a minimum requirement. If you are using Alpine Linux for the container, it might be worth it to try updating to openjdk11 to see if this works.

To verify the issue / fix (post JDK update):
1. Start up MegaBasterd 8.9 (latest as of 28 Oct 2023)
2. Add links
3. Copy and paste in a mega.nz link that includes a folder: https://mega.nz/#F!gSokWLzQ!CfTNkr4pq5BbmzGLI9Y3fQ (this is a custom windows 7 iso)
4. Verify progress

In JDK 8, you will see that nothing happens, and it stays stuck on the link verification part.

If you update to a later JDK version, it should go through without any issues.

**Comment by gauravsuman007** [comment]
This was fixed by the original author in 8.13, I tested v8.14 and it is working

https://github.com/tonikelope/megabasterd/issues/600
