### ISSUE TITLE
Any plans to update this to the latest MegaBasterd version?

### ISSUE THREAD

**Issue by leddie24** [gauravsuman007/megabasterd-docker#4]
### Idea

Hi, thanks for this docker container; just wondering if there are plans to update to the latest MegaBasterd version. Unless I'm mistaken my container is running 7.76 and the latest is 8.14

**Comment by gauravsuman007** [comment]
You can easily update it by replacing the jar file in the config folder. Megabasterd updates very frequently so I'll update the container when there are breaking changes. Or maybe around Christmas holidays ;)

**Comment by leddie24** [comment]
Thank you! Didn't know that, just getting started with linux and docker 👍

**Comment by gauravsuman007** [comment]
Just added the update steps to the documentation:
https://github.com/gauravsuman007/megabasterd-docker/blob/master/README.md#updating-the-megabasterd-app
